### PR TITLE
Fixed issue where tracking an event wasn’t possible from Objective-C code.

### LINKED ISSUE #142: can't use event Click on oc
can't use event Click on oc.........i can't  find   a  SEL  in  Tracker  about  event

### PR DESCRIPTION
**Pull request by brototyp**
Fixes #142

I also added the ObjectiveCCompatibilityChecker in the test app to ensure that we will keep the Objective-C compatibility.

### CODE REVIEW

File: PiwikTracker/Tracker.swift [hunk 1]
```diff
@@ -186,3 +186,13 @@ extension Tracker {
         queue(event: event(withCategory: category, action: action, name: name, value: value))
     }
 }
+
+// Objective-c compatibility extension
+extension Tracker {
+    
+    @objc public func track(eventWithCategory category: String, action: String, name: String? = nil, number: NSNumber? = nil) {
```
Comment (brototyp) [inline PiwikTracker/Tracker.swift]: This here is the real fix. It is not possible to call a swift method from Objective-C when one parameter is an optional primitive.

File: Example/iOS Example/ObjectiveCCompatibilityCheker.h [hunk 2]
```diff
@@ -0,0 +1,7 @@
+// We use this file to check if all calls are usable from Objective-C code.
+
+#import <Foundation/Foundation.h>
+
+@interface ObjectiveCCompatibilityCheker : NSObject
```
Comment (thorstenstark) [inline Example/iOS Example/ObjectiveCCompatibilityCheker.h]: `Checker`with `ck` ;)

Comment (brototyp) [inline Example/iOS Example/ObjectiveCCompatibilityCheker.h]: Yep, correct 😊
Just fixed that.
